---
title: "0. Set up training dataset"
author: "Xiao Yang"
date: "8/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(sf)
```

merge manually classified areas and assign image id to each polygon

```{r}
dat1 = st_read("data/lake_ice_training_data1.shp")
dat2 = st_read("data/lake_ice_training_data2.shp")
dat = rbind(dat1, dat2)

save(dat, file = "outputs/training_polygons_20190808.RData")
summary(dat)

class_count_raw = dat %>% 
  ggplot() +
  geom_bar(aes(x = class)) +
  theme(axis.text.x.bottom = element_text(angle = 45, hjust = 1)) +
  labs(
    x = "Class",
    y = "Count"
  )

class_count_raw

class_count_raw %>% 
  ggsave(filename = "figs/class_count_raw.png",
         width = 5,
         height = 4)


hl = st_read("data/HydroLAKES_polys_v10_shp/HydroLAKES_polys_v10.shp")
imgIds = read_csv("outputs/subsamples_training_lakes_20190802.csv")

dat = dat %>% 
  mutate(polygonId = 1:nrow(dat))

dat_ids = dat %>% 
  st_join(hl %>% dplyr::select(Hylak_id, Elevation), left = T) %>% 
  left_join(imgIds %>% dplyr::select(LANDSAT_SCENE_ID, Hylak_id, lif, temp), by = "Hylak_id")

dat_ids = dat_ids %>% 
  filter(!is.na(LANDSAT_SCENE_ID)) %>% 
  mutate(area = as.numeric(st_area(geometry)) / 1000000)

st_write(dat_ids, dsn = "outputs/training_polygons_ids_20190810.shp")
```


## simplified categories

```{r}
water = dat_ids %>% 
  filter(class %in% c("water", "cloudy_water")) %>% 
  mutate(sclass = "water")

ice = dat_ids %>% 
  filter(class %in% c("snow", "opaque_ice", "cloudy_opaque_ice")) %>% 
  mutate(sclass = "snow/ice")

clear_ice = dat_ids %>% 
  filter(class %in% c("clear_ice", "cloudy_clear_ice")) %>% 
  mutate(sclass = "clear_ice")

cloud = dat_ids %>% 
  filter(class %in% c("FSI_clouds")) %>% 
  mutate(sclass = "cloud")

dat_ids_sim = rbind(water, ice, clear_ice, cloud)

dat_ids_sim = dat_ids_sim %>% 
  mutate(scl_int = as.integer(as.factor(sclass)))

dat_ids_sim %>% as.data.frame %>% dplyr::select(sclass, scl_int) %>% distinct()

st_write(dat_ids_sim, dsn = "outputs/training_polygons_sim_ids_20190811.shp")

class_count = dat_ids_sim %>% 
  ggplot() +
  geom_bar(aes(x = sclass)) +
  labs(
    x = "Class",
    y = "Number of polygons"
  )

class_count

class_count %>% 
  ggsave(filename = "figs/class_count.png",
         width = 4,
         height = 4)

class_result_fig1 = dat_ids_sim %>% 
  ggplot() +
  geom_point(aes(x = temp, y = lif, color = sclass)) +
  labs(
    x = "ERA5 30-day mean SAT (ºC)",
    y = "Lake ice cover (Fmask)",
    color = "Class"
  ) +
  scale_y_continuous(labels = scales::percent_format(1), limits = c(0, 1))

class_result_fig1

class_result_fig1 %>% 
  ggsave(filename = "figs/class_result_fig1.png",
         width = 5,
         height = 5)

class_result_fig2 = dat_ids_sim %>% 
  filter(sclass != "cloud") %>% 
  mutate(ice = sclass != "water") %>% 
  mutate(source = "Visual") %>% 
  rbind(dat_ids_sim %>% 
    filter(sclass != "cloud") %>% 
    mutate(ice = lif >= 0.5) %>% 
    mutate(source = "Fmask")) %>% 
  ggplot() +
  geom_density(aes(temp, fill = ice), alpha = 0.5) +
  facet_wrap(~source, ncol = 1) +
  labs(
    x = "ERA5 30-day mean SAT (ºC)",
    y = "Density",
    fill = "Ice?"
  )

class_result_fig2

class_result_fig2 %>% 
  ggsave(filename = "figs/class_result_fig2.png",
         width = 5,
         height = 5)


```

